### ISSUE TITLE
error with pb.h

### ISSUE THREAD

**Issue by alirezainallo** [nanopb/nanopb#849] opened 2023-01-07 09:15 UTC
I want to build example/simple project for test but I give some error from <code>pb.h</code>:

![image](https://user-images.githubusercontent.com/96906718/211143306-b1258602-217b-4188-9823-3d57b850dc20.png)
please help me!

**Comment by PetteriAimonen** [comment] 2023-01-07 09:34
Have you followed the recommendations above the comment, especially the part about enabling support for C11 standard in your compiler?

If this is MSVC, probably duplicate of #844.

**Comment by alirezainallo** [comment] 2023-01-07 10:12
> Have you followed the recommendations above the comment, especially the part about enabling support for C11 standard in your compiler?
> 
> If this is MSVC, probably duplicate of #844.

thank you [PetteriAimonen](https://github.com/PetteriAimonen). I solve it. my problem was for a function that have another name in my IDE: 
![image](https://user-images.githubusercontent.com/96906718/211145161-c9d0c5e9-7935-46b3-9f4c-925216284a4b.png)
and compiler can't tell me about it because, it was a micro defined.

**Closed** 2023-01-07 11:30 UTC
