### ISSUE TITLE
oneof Exception when using Google API Annotations

### ISSUE THREAD

**Issue by frennkie** [nanopb/nanopb#413] opened 2019-07-21 11:46 UTC
I have a problem trying to use `nanopb` on a .proto file that uses Google API Annotations.

Starting with a basic .proto file (without the annotations) like this:

```
syntax = "proto3";
package v1;

service HelloWorldGreeter {
    rpc SayHelloWorld (HelloWorldRequest) returns (HelloWorldResponse) {
    }
}

message HelloWorldRequest {
}

message HelloWorldResponse {
    string message = 1;
}
```

It compiles fine.

But when I then add API annotations to it like so I get an error:

```
syntax = "proto3";
package v1;

import "google/api/annotations.proto";

service HelloWorldGreeter {
    rpc SayHelloWorld (HelloWorldRequest) returns (HelloWorldResponse) {
        option (google.api.http) = {
            post: "/api/helloworld"
            body: "*"
        };
    }
}

message HelloWorldRequest {
}

message HelloWorldResponse {
    string message = 1;
}
```

I call: `protoc.exe -I. --plugin=protoc-gen-nanopb=third_party\nanopb\generator\protoc-gen-nanopb.bat --nanopb_out=. helloworld.proto`

```
Traceback (most recent call last):
  File [...]
Exception: Callback fields inside of oneof are not supported (field get)
--nanopb_out: protoc-gen-nanopb: Plugin failed with status code 1.
```

**Comment by PetteriAimonen** [comment] 2019-07-21 19:06
Duplicate of #175

**Closed** 2019-12-16 13:34 UTC
