### ISSUE TITLE
Error "'dict_values' object does not support indexing" while compiling .proto files

### ISSUE THREAD

**Issue by Psy-Kai** [nanopb/nanopb#610] opened 2020-11-09 12:30 UTC
It seems like some python2 syntax is in `nanopb_generator.py`:

https://github.com/nanopb/nanopb/blob/9f57cc871d8a025039019c2d2fde217591f4e30d/generator/nanopb_generator.py#L990

This will lead to the error in the title.

**Comment by PetteriAimonen** [comment] 2020-11-09 13:59
Yeah, looks like this code path is uncovered by current test cases.

**Comment by Psy-Kai** [comment] 2020-11-11 11:28
It seems that there is an even bigger issue around this line. Then "fixing" this python2 syntax line via `list(dynamic_sizes.values())[0]` non compilable code will be generated.

**Comment by PetteriAimonen** [comment] 2020-11-11 12:18
Do you have a .proto file that triggers this?

**Comment by lopsided98** [comment] 2020-11-19 22:27
I can reproduce this with the following set of proto files:
```protobuf
syntax = "proto3";

import "LogMessage.proto";

message DataPacket {
    oneof packet {
        LogMessage log_message = 1;
    }
}
```
```protobuf
syntax = "proto3";

message LogMessage {
    string msg = 1;
}
```

The error only occurs if the messages are defined in different files.

**Comment by PetteriAimonen** [comment] 2020-11-20 05:21
Hmm yeah, and it even occurs when both files are passed to the generator together. I'll try to find time to take a closer look at this.

**Comment by PetteriAimonen** [comment] 2020-11-25 07:19
@Psy-Kai Do you have a .proto file that reproduces the problem with **"Then "fixing" this python2 syntax line via list(dynamic_sizes.values())[0] non compilable code will be generated."**? For the file posted by @lopsided98 that fix appears to work correctly.

**Comment by Psy-Kai** [comment] 2020-11-26 09:54
Sorry of the very late answer. I will attach some files which represents the bug (which still exists if you have a deeper structure)
[nanopb_generator_bug.zip](https://github.com/nanopb/nanopb/files/5601989/nanopb_generator_bug.zip)

**Comment by PetteriAimonen** [comment] 2020-11-26 11:28
@Psy-Kai Thanks, I was able to reproduce that bug now. Looks like it has a problem with finding the dependencies of the dependencies.

**Comment by Psy-Kai** [comment] 2021-02-08 13:18
@PetteriAimonen I just tested generating files with generator from master and it works for my proto definitions now. Thanks :)

This also fixed an size-macro ordering issue I got now ^^

**Comment by PetteriAimonen** [comment] 2021-02-08 13:29
Glad to hear that :)

**Comment by PetteriAimonen** [comment] 2021-03-22 15:15
Fix released in 0.4.5.

**Closed by PetteriAimonen** 2021-03-22 15:15 UTC
Labels: Component-Generator, FixedInGit, Priority-Medium, Type-Defect
